#!/usr/bin/env bash
# install-git-hook.sh - Installs commit-msg git hook to enforce Conventional Commits.
set -euo pipefail

TARGET_DIR="${1:-.}"

if [ ! -d "$TARGET_DIR/.git" ]; then
  echo "Error: $TARGET_DIR is not a git repository (missing .git directory)."
  exit 1
fi

# Respect core.hooksPath if configured, otherwise default to .git/hooks
HOOKS_DIR=$(git -C "$TARGET_DIR" config core.hooksPath 2>/dev/null || echo "$TARGET_DIR/.git/hooks")
mkdir -p "$HOOKS_DIR"

HOOK_FILE="$HOOKS_DIR/commit-msg"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LINTER_PATH="$SCRIPT_DIR/commit-lint.sh"

# Protect existing hook from silent overwrite
if [ -f "$HOOK_FILE" ]; then
  echo "Warning: $HOOK_FILE already exists."
  if [ -t 0 ]; then
    read -p "Overwrite? (y/N) " REPLY
    if [[ ! "${REPLY:-}" =~ ^[Yy]$ ]]; then
      echo "Aborted. Existing hook was not modified."
      exit 0
    fi
  else
    echo "Running non-interactively — overwriting existing hook."
  fi
fi

cat <<EOF > "$HOOK_FILE"
#!/bin/bash
# Automatically generated by conventional-commits skill
"$LINTER_PATH" "\$1"
EOF

chmod +x "$HOOK_FILE"
echo "✔ Installed commit-msg git hook successfully at $HOOK_FILE"
